In [1]:
import numpy as np
import cv2
import matplotlib.image as matimg
from PIL import Image

import matplotlib.pyplot as plt

In [3]:
# openCV
img_cv = cv2.imread('flying_bird.jpg')
# matplotlib
img_mat = matimg.imread('flying_bird.jpg')
# pillow
img_pil = Image.open('flying_bird.jpg')

In [4]:
print(img_cv)

[[[ 21  48  92]
  [ 19  46  90]
  [ 16  42  88]
  ...
  [  0  14  13]
  [  0  11  10]
  [  0  15  14]]

 [[ 17  44  88]
  [ 16  43  87]
  [ 15  41  87]
  ...
  [  4  20  19]
  [  1  17  16]
  [  0  13  12]]

 [[ 19  45  91]
  [ 19  45  91]
  [ 19  45  92]
  ...
  [  4  22  21]
  [  7  23  22]
  [  0  15  14]]

 ...

 [[ 29  57  88]
  [ 36  64  95]
  [ 40  65  97]
  ...
  [  1 102  77]
  [  2  98  74]
  [  1  97  73]]

 [[ 36  62  92]
  [ 38  64  94]
  [ 39  65  95]
  ...
  [  1 102  77]
  [  3  99  75]
  [  1  97  73]]

 [[ 36  62  92]
  [ 34  60  90]
  [ 34  60  90]
  ...
  [  0 100  75]
  [  1  97  73]
  [  1  97  73]]]


In [4]:
print(img_mat)

[[[ 92  48  21]
  [ 90  46  19]
  [ 88  42  16]
  ...
  [ 13  14   0]
  [ 10  11   0]
  [ 14  15   0]]

 [[ 88  44  17]
  [ 87  43  16]
  [ 87  41  15]
  ...
  [ 19  20   4]
  [ 16  17   1]
  [ 12  13   0]]

 [[ 91  45  19]
  [ 91  45  19]
  [ 92  45  19]
  ...
  [ 21  22   4]
  [ 22  23   7]
  [ 14  15   0]]

 ...

 [[ 88  57  29]
  [ 95  64  36]
  [ 97  65  40]
  ...
  [ 77 102   1]
  [ 74  98   2]
  [ 73  97   1]]

 [[ 92  62  36]
  [ 94  64  38]
  [ 95  65  39]
  ...
  [ 77 102   1]
  [ 75  99   3]
  [ 73  97   1]]

 [[ 92  62  36]
  [ 90  60  34]
  [ 90  60  34]
  ...
  [ 75 100   0]
  [ 73  97   1]
  [ 73  97   1]]]


In [ ]:
img_pil
img_pil_arr = np.array(img_pil)


In [ ]:
cv2.imshow('window_name', img_cv)
cv2.imshow('matplotlib', img_mat)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
plt.figure(figsize=(15,6))
plt.subplot(1,3,1)
plt.imshow(img_cv)
plt.axis('off')
plt.title('OpenCV BGR')

plt.subplot(1,3,2)
plt.imshow(img_mat)
plt.axis('off')
plt.title('Matplotlib RGB')

plt.subplot(1,3,3)
plt.imshow(img_pil_arr)
plt.axis('off')
plt.title('Pillow RGB')

In [ ]:
img_cv.shape

In [ ]:
#numpy slicing
# BGR
b = img_cv[:,:,0]
g = img_cv[:,:,1]
r = img_cv[:,:,2]

In [ ]:
cv2.imshow('blue channel', b)
cv2.imshow('green channel', g)
cv2.imshow('red channel', r)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
b, g, r = cv2.split(img_cv)

In [ ]:
b.shape, g.shape, r.shape, img_cv.shape

In [ ]:
# converting image colors
cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB)