In [1]:
import numpy as np
import cv2


In [18]:
img = cv2.imread('friends.jpg')
cv2.imshow('image', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [19]:
# load cascade classifier
haar = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [20]:
image = img.copy()
# step 1: convert image to grayscale
grayscale_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# step 2: apply grayscale image to cascade classifier
face_rect = haar.detectMultiScale(grayscale_img, 1.3,5)
# step 3: draw bounding box
for x,y,w,h in face_rect:
    cv2.rectangle(image,(x,y),(x+w, y+h),(0,255,0),2)
    
#displaying detected faces
cv2.imshow('Detected faces',image)
cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
print(face_rect)

[[149 259  30  30]
 [126   4  68  68]
 [128 107  96  96]
 [255  90  95  95]
 [407  92  95  95]]


### Real Time Face Detection using OpenCV

In [26]:
cap = cv2.VideoCapture('video.mp4')
# if the video is corrupted or someting is wrong with the video, than that's the information we can able to get find in the ret,
# as a True or False.If ret is false, then we need to break the loop. Otherwise, we will show the frame.

while True:
    ret, frame = cap.read()
    if ret == False:
        break
        
    image = frame.copy()
    # step 1: convert image to grayscale
    grayscale_img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    # step 2: apply grayscale image to cascade classifier
    face_rect = haar.detectMultiScale(grayscale_img, 1.3,5)
    # step 3: draw bounding box
    for x,y,w,h in face_rect:
        cv2.rectangle(image,(x,y),(x+w, y+h),(0,255,0),2)
    cv2.imshow('face detection', image)
        
    if cv2.waitKey(10) == 27: # 27 is for ESCAPE key
        break
        
cap.release()
cv2.destroyAllWindows()